### ISSUE TITLE
[BUG] Issues with NFS: Most Wanted

### ISSUE THREAD

**Issue by Electry** [Electry/VitaGrafixPatchlist#7]
To be able to run NFS:MW at a full fat 960x544 (default is 640x368) some sacrifices had to be made. Specifically, I had to find an extra 5 MBs of video memory so that larger render buffers could be created. Because the game already uses all 118 MBs the vita has, I cut 5 MBs away from the Parameter Buffer used by vita's rendering library.

I highly suspect that this is why you see sudden drops to < 15 fps when you enter certain areas in the game while playing at 960x544 with 4x MSAA, which makes it pretty much unplayable. If you want to keep 4x MSAA, I recommend using <= 840x476 (this only requires extra 3 MBs).

Furthermore, with some resolutions, lighting and particles cause artifacting as shown on the screenshot below. Usually I was able to fix this by setting the width and height to a multiple of 32 (e.g. 832x480 worked for me IIRC).

![2018-12-30-003450](https://user-images.githubusercontent.com/12598379/50555095-e4e8d480-0cc7-11e9-8be7-d182769d585a.png)

![2018-12-30-232253](https://user-images.githubusercontent.com/12598379/50555104-08ac1a80-0cc8-11e9-83ed-2e05252a5f00.png)

**Comment by nad45** [comment]
Can you disable the MSAA?

**Comment by ImplyingKinpatsu** [comment]
832x480 with x1/x2 MSAA  and 800x448 produce a silhouette of the whole frame flattened to the left side when you burnout and I found a light source that clipped through everything in Hodges Airfield. x4 MSAA worked fine.
![800x448 avi_snapshot_00 09_ 2019 01 01_02 52 43](https://user-images.githubusercontent.com/25698617/50571810-f803af00-0d70-11e9-9a14-c845eba1a099.jpg)
![800x448 avi_snapshot_00 10_ 2019 01 01_02 53 07](https://user-images.githubusercontent.com/25698617/50571811-f803af00-0d70-11e9-986f-390710b5bf85.jpg)
Vitagrafix v4.0 Alpha-2

**Comment by EnekoT2001** [comment]
Hi, how can I disable MSAA? I tried writing MSAA=1/MSAA=4/MSAA=4x... And nothing :c just patch error.

**Comment by Electry** [comment]
MSAA=0
MSAA=0x
MSAA=1
MSAA=1x

any of these should work. Make sure you have the new Alpha-2 VitaGrafix build as I've added a few required things for this.

**Comment by eddyfire** [comment]
Tried 960x544 with MSAA=0, and it turns out great. Minimal frame drop. Great difference from the default resolution. 🙂 Thanks Electry!

**Comment by Babbosh** [comment]
I agree with @eddyfire. Just tested it with 544<0 and it looks sooo much better. The game now is really gorgeous. 
Thanks for reviving another great game.

**Comment by ImplyingKinpatsu** [comment]
It should also be noted that x1 MSAA disables the AI's lights and with x2 enabled, lights will only render when they're on the left side of the screen

(544/x2 MSAA)
![drive_to_mostwanted1_544_x2msaa avi_snapshot_00 02_ 2019 01 03_07 12 07](https://user-images.githubusercontent.com/25698617/50641950-e401ae00-0f26-11e9-8cd3-c85d941084ac.jpg)
(544/x1 MSAA)
![drive_to_mostwanted1_544_nomsaa avi_snapshot_00 05_ 2019 01 03_06 46 45](https://user-images.githubusercontent.com/25698617/50641177-6472df80-0f24-11e9-9319-1080fd849bad.jpg)
(544/x4 MSAA)
![drive_to_mostwanted1_544_x4 avi_snapshot_00 46_ 2019 01 03_06 51 20](https://user-images.githubusercontent.com/25698617/50641179-650b7600-0f24-11e9-8c2e-7e140cbbb14b.jpg)

**Comment by yeqing1990** [comment]
The best parameter is 832x480, msaa=4

**Comment by Babbosh** [comment]
@justalex95  No. It's a typical hardware limitation. Mobile devices are battery bounded therefore sacrifices needs to be made. 
In few words battery on the vita has to give juice to the Cpu, gpu, screen from a 3.7v lipo battery and potential energy and current on these batteries (like any other) has a clear limit. Commercially you will have to sacrifice battery duration for performance and so it will be just idiotic to have an handheld that lasts 1 hour with a single charge. Where is the fun in having an handheld that it needs to be plugged in for most of its time? 
I already had to mod my battery to 4000mah cause the 2200mah original battery was really ridiculous ( I am currently trying to find a 6000mah battery that I can squeeze in).
 
On the other hand a ps tv doesn't  will always be used plugged into a wall socket and a 3rd party monitor/tv, so current limitations are not in the equations. 

It's  the same thing with gaming laptops. 
1) They have for example a gtx 1080m (mobile) but it is around 30%/40% slower than the desktop counterpart due to transistor downsizing and battery limitations
2) When unplugged the system will automatically underclock in order to save battery, that is why they call the "Desktop replacements" as you have to keep them plugged in in order to enjoy max performance.

**Comment by justalex95** [comment]
ah, ok. so its like a laptop plugged in on high performance mode compared to a laptop on battery.

Found it strange that the difference was noticeable especially because its the same hardware with the addition of upscaling. I didnt think it would be faster with the extra load

**Comment by Babbosh** [comment]
@justalex95  Well It's the only thing  I can think off. I don't own a ps tv and don't know which amperage its power adapter has. 
Usually that is the reason handhelds perform poorly compared to desktop. The current that a 3.7 lipo can release at once to power cpu/gpu/screen/speakers etc... it's not comparable to a console with the same specs that has a 1/2A. 
You can see it when there are triple A games that require 444mhz, the screen backlight can only go up to a certain point as the battery cannot provide enough current to everything. 

This will happen until new form of battery that can store and release great quantity of energy at once will be invented such as the supercapacitors. Caps at the moment can release great quantity of electrons in a millisecond but the problem is that in that same amount of time release all their stored energy. A 5v supercapacitor would be perfect but very much overkill for the ps vita ehehehe.

**Comment by justalex95** [comment]
after messing around with the settings i found 912x416 for high fps and 896x428 to be the tipping point for graphics but still run very smoothly.

912x416 has the smoke lines but as far as i can tell the 896x428 has no graphical glitches

**Comment by justalex95** [comment]
I think I may have found the near perfect settings for resolution.

931x427 w/MSAAx4 @500mhz, every effect works, FPS is insanely smooth and consistent, there's little to no slowdown, no stutter, all the lighting effects work and the cars look semi-hd, its the only way I can describe it.

It hasnt glitched out or had any missing effects. it plays perfectly with these settings

**Comment by Babbosh** [comment]
> QUOTE:
> You can see it when there are triple A games that require 444mhz, the screen backlight can only go up to a certain point as the battery cannot provide enough current to everything.
> 
> I worked out you can bypass the limit by setting lolicon to 500mhz in livearea and setting it for main and default. after you do that, you can go to full brightness. I've played for 1 and a half hours at full brightness full clocks on NFS and it manages it fine.
> 
> 931x427 runs a bit slower at night time, but its nowhere near game breaking and as a trade off for higher resolution its not bad
> 
> EDIT: PSTV plays 931x427 smoother than the vita, might be a possible vitagrafix configurator default value given the amount of resolutions possible on NFS:MW

I maybe made a bit of confusion with my reply. What I meant was that 444mhz coupled with high brightness means high current output  which might result in heat increase on the lipo layers. The low brightness is nothing more than a safety measure.

If I were you I would be careful with, lipo battery have exploded on me for much less strain and I can tell you than when they explode they have the effect of a mini napalm bomb. 
Take it easy and keep the battery temp monitored.
Actually don't do it anymore, stay safe.

**Comment by adrianbass360** [comment]
First, I just wanted to say great work Electry, never been prouder of my vita =D. Second, for some reason vitagrafix isn't working on this game specifically. All others are fine. But for NSMW, when I start the game on the top left corner I get "Default" instead of "960x544", and yup after the 3 min intro the resolution stays low... Any Idea why?

**Comment by adrianbass360** [comment]
Also I can't seem to find NSMW on vitagrafix configurator. Hmmm...

**Comment by justalex95** [comment]
Thanks for the info babbosh I didnt realise they could do that. I dont usually play full brightness I just tested it out to see if it could handle it. 

Need for speed gets hot after about 2 hours if I speed round the map for prolonged periods I'm guessing due to the amount of loading it needs to do.

I've been trying 832x511 as a resolution and its a strange one... general driving is super fast and stable but when it comes to mountains or certain areas of the map (there's about 5 areas) it slows down to load. 

lower resolutions dont play as stable or look as good, so I was wondering if anyone knew if part of the 5 mb taken from the rendering process could be reallocated back to it to accommodate the 832x511 resolution. I have no idea how to do it myself but If someone knows how, I'll give it a try. 

so instead of 5 mb needed for the GBuffer at 960x544 (which is unplayable with msaax4) I'm suggesting maybe just taking 3mb  for the 832x511 w/msaax4 resolution for example. 

I dont know anything about this kind of thing so if I'm barking up the wrong tree, or the memory is dynamically allocated when the game is loaded, just ignore me.

**Comment by justalex95** [comment]
> First, I just wanted to say great work Electry, never been prouder of my vita =D. Second, for some reason vitagrafix isn't working on this game specifically. All others are fine. But for NSMW, when I start the game on the top left corner I get "Default" instead of "960x544", and yup after the 3 min intro the resolution stays low... Any Idea why?

check your config file, make sure you have the right ID for the region of NFS that your using and use the correct syntax for settings.

the plugins working it'll probably be a PCSB00089 instead of PCSE00089 or something like that. I literally woke up this morning and had the same problem, the config file deleted the NFS entry completely, but I put the settings back in and it works fine now

**Comment by adrianbass360** [comment]
PCSB00089 is the European version. So this will only work with European version?

**Comment by adrianbass360** [comment]
This is what is currently on the patchlist.txt. I want it at 960x544, no msaa for the US version, PCSE00089:

# Need for Speed: Most Wanted [EU 1.01]
[PCSB00183,eboot.bin,0x36DC8D31]
# Need for Speed: Most Wanted [US 1.01]
[PCSE00089,eboot.bin,0x36DC8D31]
# Need for Speed: Most Wanted [JP 1.01]
[PCSG00106,eboot.bin,0x36DC8D31]
@IB
0:0x2F8D60 t2_mov(1,1,<ib_w>)
0:0x2F8D68 t2_mov(1,1,<ib_h>)
# What are these ?!
0:0x54DCB2 t2_mov(1,2,<if_gt,<*,<ib_w>,<ib_h>>,<*,840,476>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xB00000,<if_eq,<msaa>,1,0xD00000,0xE00000>>,0xB00000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,720,408>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xD00000,<if_eq,<msaa>,1,0xE00000,0xF00000>>,0xD00000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,640,368>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xF00000,0x1000000>,0xF00000>,0x1000000>>>)
1:0x331C uint32(<if_gt,<*,<ib_w>,<ib_h>>,<*,840,476>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x15AA000,<if_eq,<msaa>,1,0x13AA000,0x12AA000>>,0x15AA000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,720,408>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x13AA000,<if_eq,<msaa>,1,0x12AA000,0x11AA000>>,0x13AA000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,640,368>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x11AA000,0x10AA000>,0x11AA000>,0x10AA000>>>)
@MSAA
# GBuffer
0:0x2F8C6A t1_mov(1,<msaa>)
# Lighting accumulation buffer
0:0x2F8B72 t1_mov(0,<msaa>)

**Comment by adrianbass360** [comment]
This is what is currently on the patchlist.txt. I want it at 960x544, no msaa for the US version, PCSE00089:

# Need for Speed: Most Wanted [EU 1.01]
[PCSB00183,eboot.bin,0x36DC8D31]
# Need for Speed: Most Wanted [US 1.01]
[PCSE00089,eboot.bin,0x36DC8D31]
# Need for Speed: Most Wanted [JP 1.01]
[PCSG00106,eboot.bin,0x36DC8D31]
@IB
0:0x2F8D60 t2_mov(1,1,<ib_w>)
0:0x2F8D68 t2_mov(1,1,<ib_h>)
# What are these ?!
0:0x54DCB2 t2_mov(1,2,<if_gt,<*,<ib_w>,<ib_h>>,<*,840,476>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xB00000,<if_eq,<msaa>,1,0xD00000,0xE00000>>,0xB00000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,720,408>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xD00000,<if_eq,<msaa>,1,0xE00000,0xF00000>>,0xD00000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,640,368>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0xF00000,0x1000000>,0xF00000>,0x1000000>>>)
1:0x331C uint32(<if_gt,<*,<ib_w>,<ib_h>>,<*,840,476>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x15AA000,<if_eq,<msaa>,1,0x13AA000,0x12AA000>>,0x15AA000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,720,408>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x13AA000,<if_eq,<msaa>,1,0x12AA000,0x11AA000>>,0x13AA000>,<if_gt,<*,<ib_w>,<ib_h>>,<*,640,368>>,<if_eq,<msaa_enabled>,1,<if_eq,<msaa>,2,0x11AA000,0x10AA000>,0x11AA000>,0x10AA000>>>)
@MSAA
# GBuffer
0:0x2F8C6A t1_mov(1,<msaa>)
# Lighting accumulation buffer
0:0x2F8B72 t1_mov(0,<msaa>)

**Comment by justalex95** [comment]
You've not entered NFS into the config file, thats why its not working. Go into config.txt in the same directory as patchlist.txt

You'll see game id's followed by enabled=1, osd=1, etc

copy and paste one of them and change the game ID to PSCE00089. the only options you need for nfs after enabled and OSD is IB=960x544 and MSAA=1x (no AA)  for example. if fps=60 is there, delete it.

save and exit and it should work

**Comment by adrianbass360** [comment]
Thank! I had actually figure it with something you said earlier haha. Just need to add MSAA=1x. Again, thanks for your help !! (it did get deleted on config.txt like you mentioned)

**Comment by adrianbass360** [comment]
I'm trying it with the resolution of Ninja Gaiden Sigma (864x480) with MSAA set at 4x and plays and looks amazing!

**Comment by adrianbass360** [comment]
I'm playing it with Ninja Gaiden Sigma's resolution (864x480) + MSAA=4x and it's looks amazing! Much better than the original 640x384 haha

**Comment by justalex95** [comment]
Babbosh, if you can get your hands on a developer edition vita, they had 1gb of ram instead of 512mb, but they are rare

**Comment by Babbosh** [comment]
@justalex95 No, it's the video ram that I wanna look into. I think Vita  has 128Gb but effective is a bit lower than that. 
It will take a while and possibility of success is very low but trying is for free.

**Comment by Babbosh** [comment]
@justalex95 We are clearly going off topic, just let's end it here. Ehehe

**Comment by justalex95** [comment]
hope you get it working babbosh, will be interesting to see

**Comment by Babbosh** [comment]
@justalex95  Thanks

By the way, I have tried 832x480 msaa/4 and I could clearly see misplaced reflection when I was on one of the bridges and had the camera facing the side of the car.

**Comment by yeqing1990** [comment]
@Electry 
The game has a 480X272 rendering, is it a special effect resolution? For example: car lights, shadows. I found the address, but I don't know how to modify it. The address is w:812F9180h:812F918C. I try to write directly into the code and report an error.

**Comment by ezzinekaemel** [comment]
> @justalex95 No. It's a typical hardware limitation. Mobile devices are battery bounded therefore sacrifices needs to be made.
> In few words battery on the vita has to give juice to the Cpu, gpu, screen from a 3.7v lipo battery and potential energy and current on these batteries (like any other) has a clear limit. Commercially you will have to sacrifice battery duration for performance and so it will be just idiotic to have an handheld that lasts 1 hour with a single charge. Where is the fun in having an handheld that it needs to be plugged in for most of its time?
> I already had to mod my battery to 4000mah cause the 2200mah original battery was really ridiculous ( I am currently trying to find a 6000mah battery that I can squeeze in).
> 
> On the other hand a ps tv doesn't will always be used plugged into a wall socket and a 3rd party monitor/tv, so current limitations are not in the equations.
> 
> It's the same thing with gaming laptops.
> 
> 1. They have for example a gtx 1080m (mobile) but it is around 30%/40% slower than the desktop counterpart due to transistor downsizing and battery limitations
> 2. When unplugged the system will automatically underclock in order to save battery, that is why they call the "Desktop replacements" as you have to keep them plugged in in order to enjoy max performance.

Can you tell us more about your custom 4000mah battery. Extensive readings show that there are hardcoded limitations in the hardware itself where even if you install a bigger battery of the same chemistry and voltage, it will Not charge past the OG mah (2210).

If you did actually managed to charge your Vita up to 4000mah (with an Amp meter) or have seen about double battery life, then please report your findings and soldering pics.

Since there are no social component on github to be in touch, please create a reddit post and link it here. Thank you on behalf of the entire community :)

**Comment by adrianbass360** [comment]
In case anyone is still interested in the best settings for this games, I found them. Keep MSAA at 4x, but switch over resolutions to 704x544. This runs very smooth and looks sharper than 832x480 since 544 is the vita's horizontal resolution count. Also no glitches so far. The difference between these and the default setting are like night and day! It doesn't even feel like the same games anymore lol

**Comment by EnekoT2001** [comment]
> In case anyone is still interested in the best settings for this games, I found them. Keep MSAA at 4x, but switch over resolutions to 704x544. This runs very smooth and looks sharper than 832x480 since 544 is the vita's horizontal resolution count. Also no glitches so far. The difference between these and the default setting are like night and day! It doesn't even feel like the same games anymore lol

Tbh, I tried it for a little bit and seems to work great, with 500mhz cpu oc it has barely unnoticeable slowdowns when there's a lot of smoke etc.

**Comment by adrianbass360** [comment]
Yeah, all the effects are there and the image looks crysp. Currently looking for a good Spotify racing playlist to go along with it because honestly the ost is horrible haha

**Comment by justalex95** [comment]
I prefer 736x528 MSAAx4, gives a bit more horizontal smoothness and the vertical res uses more gpu so lowering it to 528 gives a speed boost without lmpacting visual clarity at all really. 

I found 704x544 to slowdown too much at night time and if you did a burnout with alot of smoke it would really slowdown

**Comment by adrianbass360** [comment]
I've noticed it too at night (or when your headlights are on really, must take up more RAM),  but it's very minor and usually only happens when you're in the middle of nowhere or making a crazy U-turn, not enough bother me (races are pretty much flawless). I prefer this since off-setting the horizontal count even by 1 (543) introduces the horizontal blur, which gets rid of the nice sharpness =/

**Comment by adrianbass360** [comment]
Yeah I've noticed a tiny bit slow downs with 704x544 at night too (or when your headlights are on really, must take up more RAM), but it's very minor and usually only happens when you're in the middle of nowhere or making a crazy turn, not enough bother me (actual races are pretty much flawless, and never broken skid lines never happen). I prefer this since off-setting the horizontal count even by 1 (543) introduces the horizontal blur, which gets rid of the nice sharpness =/.

**Comment by justalex95** [comment]
if the lighting and smoke resolutions could be reduced, the game would run alot faster, they kill frames. the smoke lines means less rendering for the gpu even though its a glitch so its preference. 

I feel higher fps makes the cars look sharper so opted for the glitched smoke @720x544

**Comment by EnekoT2001** [comment]
> if the lighting and smoke resolutions could be reduced, the game would run alot faster, they kill frames. the smoke lines means less rendering for the gpu even though its a glitch so its preference.
> 
> I feel higher fps makes the cars look sharper so opted for the glitched smoke @720x544
> 
> EDIT:There's a specific road 2 minutes away from a GTR in the city that goes round in a circle and round a few mountains that has horrible slowdown, I test that area and then the abandoned airport.
> 
> If they dont slowdown the rest of the game is playable even at night, in case there's anyone else who wants to tinker with the resolution to find one that best suits their preferences, the GTR's a fast enough car to test it as well. @720x544 these areas have no slowdown in daylight and a half second blip at night.
> 
> if I'm honest I wouldnt have tinkered around with the resolution again if @adrianbass360 hadnt posted his findings, I'm off to complete it for a second time now! great find

Tbh, the game is locked at 30fps so idk if it makes any difference to not get 25-ish fps when there's a lot of smoke. But idk those are my preferences xD. Great research what we made here btw

**Comment by adrianbass360** [comment]
@justalex95 Yeah those are the 2 areas I test out too haha. That's what I meant by in the middles of nowhere and when making turns. I don't mind it however since all glitches are gone with 704x544. 736x544 would be perfect but with those setting you do get lag a lot everywhere. But glad I could help!

**Comment by justalex95** [comment]
I found a very cool loophole? I guess... certain games can be set past native resolutions.

I've made a post here: https://github.com/Electry/VitaGrafixPatchlist/issues/52

tokyo xanadu, street fighter IV and Soul Sacrifice delta can be set to ridiculously high resolutions without glitches or crashes (tokyo xanadu has slowdowns and I havent tested it anywhere near as much as the rest of the games, but no crashes about an hour in)

Its amazing the vita is categorised as a failed console, its insanely capable, even by todays standards

**Comment by adrianbass360** [comment]
@justalex95 And this actually makes games look better!?

**Comment by Errol1886** [comment]
@adrianbass360 There are some games on the PS Vita that have anti-aliasing issues even when they are running at PS Vita's native resolution. Running those games at a higher resolution beyond 960x544 gets rid of all the anti-aliasing issues in those games.

**Comment by justalex95** [comment]
tokyo xanadu looks unreal, there's a noticeable difference in soul sacrifice and street fighter IV looks like 1080p.

I'll try and find the link I had for some screen shots

**Comment by justalex95** [comment]
Try this resolution for Need for speed, 640x608, MSAAx4, I dont know why but the shadows and lighting seem more realistic and reflections quality has gone way up.

you'll need to try it to see what I mean, I love the look of this one its like cinematic lighting and shadows

**Comment by adrianbass360** [comment]
I think these setting are more fitted for the vita tv 😅. If I go over 544 on the vita I have to drop down the vertical pixel count and I'd hate to drop it any less than 704. But I tried them, surprised they actually work!

**Comment by justalex95** [comment]
does it actually look any different from 704x544 or am I just seeing things? :D haha the reflections definitely look alot sharper which for me makes the cars look alot better

**Comment by adrianbass360** [comment]
Umm, to me it looked a little different but I'm pretty happy with 704x544 😁. It does have some slow downs here and there, but not enough to be an issue plus the image looks amazing, closest thing to 960x544 without any any serious flaws, namely the occasional 25 fps during the night.

**Comment by EnekoT2001** [comment]
> Umm, to me it looked a little different but I'm pretty happy with 704x544 ![😁](chrome-extension://cahedbegdkagmcjfolhdlechbkeaieki/images/apple/1f601.png). It does have some slow downs here and there, but not enough to be an issue plus the image looks amazing, closest thing to 960x544 without any any serious flaws, namely the occasional 25 fps during the night. But I don't have the vita tv so there I can't really say much.

Are you using LOLIcon to overclock it to the max for your testing? This gives me a little boost tbh. Not a lot in this game but always helps + it isn't real overclocking bc is in the Vita's firmware, but no one ever used it, so it's safe

**Comment by adrianbass360** [comment]
@EnekoT2001 Oh yeah definitely, 500mhz. Plus I'm running my games off an sd2vita adapter, which makes all loading times faster. Also it's good to turn off the wifi if not in use since that takes up some ram. I do however use the vida media player while turning off the built in one used on NSMW, so I'm not sure if that trades off or not...

**Comment by EnekoT2001** [comment]
> @EnekoT2001 Oh yeah definitely, 500mhz. Plus I'm running my games off an sd2vita adapter, which makes all loading times faster. Also it's good to turn off the wifi if not in use since that takes up some ram. I do however use the vida media player while turning off the built in one used on NSMW, so I'm not sure if that trades off or not...

Idk about the media player and I use a sd2vita and oc to 500mhz as well haha

**Comment by justalex95** [comment]
yeah 500mhz, airplane mode on, class 10 sd2vita and one of these resolutions (some of them are more responsive, pixel counts in brackets as a guide for fps) 704x544(382976), 704x560(394240), 720x544(391680), 656x608(398848) or 640x608(389120)

all of them play slightly different, I like the super reactive res's, so the ones with the glitchy smoke haha, thought I'd list all the working resolutions for reference. 656 and 720 have glitchy smoke

**Comment by adrianbass360** [comment]
You guys reminded me of to something, it does make a difference between of putting it on airplane mode vs simply just turning the wifi off. It runs near perfect at 704x544 with airplane mode on. Thanks, can't believe I had forgotten that lol

**Comment by olokos** [comment]
There's now a plugin called NoPowerLimits by @Electry which allows for 500MHz overclock and maximum brightness, but this has gone way off topic now.

Is there any way to unlock the actual framerate for that ultra smooth 60fps experience? I would try 240x240 if we could actually reach over 30 fps in this game. 

Even if there's a way that speeds up the game, maybe we can patch the game speed aswell?

**Comment by EnekoT2001** [comment]
> There's now a plugin called NoPowerLimits by @Electry which allows for 500MHz overclock and maximum brightness, but this has gone way off topic now.
> 
> Is there any way to unlock the actual framerate for that ultra smooth 60fps experience? I would try 240x240 if we could actually reach over 30 fps in this game.

Yep, the game speed is tied to the FPS :c until now there isn't a way to patch the game speed in vitagrafix (at least 0 known game patches like this as of right now)

**Comment by justalex95** [comment]
you've been able to have 500mhz and full brightness by setting the clock speed to 500mhz and setting it as main for ages. if it stops the wireless being turned off, thats pretty handy

**Comment by olokos** [comment]
@EnekoT2001 can you link the unlocked FPS patch and possibly some guide on how those patches are made? I could take a moment and **try** to figure it out

@justalex95 that's the main point of this plugin, 
I haven't even noticed wifi dropping when using 500MHz and full brightness with WiFi as I mainly use my vita at night/evening and after installing this plugin I just take it for granted now. :)

**Comment by Electry** [comment]
Original issue fixed in https://github.com/Electry/VitaGrafixPatchlist/commit/cf5f046e9d1dcff52522bf7311c3a93307c8b04c
